services:
  php-cli:
    build:
      context: ./
      dockerfile: .docker/php-cli/Dockerfile
    volumes:
      - .:/application

  php-rector:
    build:
      context: ./
      dockerfile: .docker/php-rector/Dockerfile
    volumes:
      - .:/application
